### PR TITLE
Added script function for getting clFPS

### PR DESCRIPTION
**Pull request by florczakraf**
Use case: displaying player's fps to other players in codjumper mod.

### CODE REVIEW

**Comment by T-Maxxx** [comment]
Pretty useless for jumping needs since updating once per second.

**Comment by florczakraf** [comment]
That's the best I can get with our mod since I don't have whole source code. Therefore I can't recompile the mod with additional menus. We use user cvars for that at the moment but it requires user to manually type `/setu com_maxfps  ...` in console which is unacceptable. Do you have a better idea?

**Comment by T-Maxxx** [comment]
Add `setu...` to fps change bind. Or find other mod. What is your mod?

**Comment by florczakraf** [comment]
Well, it's an old mod actually. Created by our former clan member and his
friend. They no longer have the source. It's really easy to add server side
features to it but it's lacking two important client-side menus: for
getting values of cvars and for execing anything on the client side.

**Comment by IceNinjaman** [comment]
Okay added it but not sure how useful it really is.

**Pull request merged**
