### PR TITLE
Changed frequency of clFPS updates

### PR DESCRIPTION
**Pull request by florczakraf**
Quoting @T-Maxxx from #43:
> Pretty useless for jumping needs since updating once per second.

I wrote a couple of lines to increase frequency of clFPS updates. I can understand if you don't want this to be merged into master since it's use case is really limited.

### CODE REVIEW

**Comment by T-Maxxx** [comment]
If it works - it'll be great.

**Comment by florczakraf** [comment]
Yeah, I added some fps interpolation in gsx [script](https://gist.github.com/florczakraf/76bd4adb3df3e13caedf7d1d1338164b) and it does it's job.

**Comment by T-Maxxx** [comment]
cl->clFrameCalcTime - means 'when server must recalculate client fps', not 'last calculation time'. Code looks good but you have changed meaning of field in structure and it may cause unexpected problems in other places.

**Comment by florczakraf** [comment]
No longer needed since @IceNinjaman made some changes directly on master.

**Pull request closed without merging**
