### PR TITLE
Random map rotation.

### LINKED ISSUE #4: Cvar for random map rotation
Currently the game only supports a set map rotation, meaning the order you specify in `sv_mapRotation`. Would be great to have an `sv_randomMapRotation` (why is that `sv_` in front anyway?), which randomly rotates through the maps in the list.

### LINKED ISSUE #33: Change serverconditions url to point to this repository
When lauching the server you currently get the following message:
```
By using this software you agree to the usage conditions you can find at http://cod4x.me/serverconditions.html
```

This url is currently just a link to the thread at the old forum. Since this forum is eventually going to be removed, this should be changed to point to this repository instead (because it's in the README.md).

### PR DESCRIPTION
**Pull request by T-Maxxx**
Cvar: sv_randomMapRotation <bool>
Fixes #4
Fixes #33

### CODE REVIEW

**Comment by PureTryOut** [comment]
Tested this, works great! Thanks for making this, now I can finally get rid of the hackish GSC code I used for this feature.

**Comment by PureTryOut** [comment]
(note: change `Issue #4` to `Fixes #4` or `Resolves #4` to automatically close the related issue when this PR is merged)

**Comment by IceNinjaman** [comment]
Okay well thank you for creating this. However few things:
1. The pause in compile scripts make some sense especially when you run this scripts with a double click.
2. Try to avoid functions like HeapAlloc(), malloc(), calloc(), strdup() if it is possible to avoid them. In you case you can just use a stack allocated variable instead.
Also you forgot to check if return value of calloc() is maybe NULL.
Just use a stack allocated array. Memset it and it should be fine.
3. Rename the function Com_Random into Com_RandomInt

Thank you.

**Comment by IceNinjaman** [comment]
Thank you.

**Pull request merged**
